OPS otazky a opravy stavajicich
holubond/szmgr pull request #30
Opened 2024-01-26 15:04 UTC by simonf-dev

2024-01-26 16:44 UTC, holubond commented
Klobouk dolů za kus odvedené práce a chuť to všechno přidat sem!

Každopádně jde o obří PR, takže mi bude chvíli trvat, než se tím prokoušu (k některým věcem budu mít pravděpodobně připomínky). Pokud ten proces chceš urychlit, rozbij to na jednotlivé feature branche (věci co jsou good to go můžu schválit rovnou).

2024-01-26 16:52 UTC, holubond commented
...podle aktivity koukám, že vývoj stále probíhá... Mám zrušit PR?

2024-01-26 20:14 UTC, simonf-dev commented
V pohodě, můžeš se na to mrknout, budu zatím přispívat do jinýho branche a do mainu už pushovat nebudu... takže PR bude stabilní

2024-01-27 22:05 UTC, holubond commented
@simonf-dev 
> V pohodě, můžeš se na to mrknout, budu zatím přispívat do jinýho branche a do mainu už pushovat nebudu... takže PR bude stabilní

Ok, ale nedávej vše do jedné větve, dělej jednotlivé feature branche, jinak na opravu budu potřebovat dlouhý čas, který se mi blbě hledá.

2024-01-28 12:13 UTC, holubond requested changes
Díky za obsáhlý PR. Pro příště ho prosím rozbij do série menších (ideálně dle featur), snadněji se to pročítá, kontroluje a zajišťuje kvalita. Takto máš k PR 86 připomínek :) Zároveň by se měl dělat PR až v momentě, kdy považuješ větev za dokončenou...

Zkus prosím dodržovat jednotný formát dokumentů, pár zásad jsem zmínil v jednom z komentářů, asi budu muset udělat contribution guide. Často jsem něco vytknul na jednom místě, stejný problém se ale mnohdy vyskytuje vícekrát. 

Největší problém vidím v přílišné "ukecanosti" - často dost obšírně rozebíráš koncepty a máš poměrně vysoké text-to-information ratio. Taky vidím potenciál ke zlepšení v tom, jak skáčeš v jednotlivých úrovních - často píšeš o nějakém high-level konceptu a hned na to skočíš do velkých detailů...

Každopádně jsi odvedl kus práce, díky za něj!

2024-01-28 12:13 UTC, holubond commented on 2_kvalita_kodu.md
> +    - u UI systému například dodržování standardů používání id/class názvů atd.
Jak to souvisí s testovatelností?

2024-01-28 12:13 UTC, holubond commented on 2_kvalita_kodu.md
> +    - udržování updated dependencí
*aktualizovaných* - e.g. Dependabot

2024-01-28 12:13 UTC, holubond commented on 2_kvalita_kodu.md
> +        - důležitá je konzistence napříč codebase (ideálně stavěná na standardech daného jazyka) - například můžu definovat, že `check*()` metody vrací true/false a `verify*()` vyhazují vyjímky
Jsou jazyky, kde by tento příklad porušoval konvence - navrhuju ponechat původní verzi

2024-01-28 12:13 UTC, holubond commented on 2_kvalita_kodu.md
> +    - např. v Pythonu (a jiných jazycích) se dost často vyplácí přidávat k existujícím funkcím optional variables -> funkce se pro existující volání chová stejně, ale se změnou nového atributu je mož
Toto je dost specifické pro interpretované jazyky. V běžných jazycích volitelné parametry nejsou a mít parametr na základě kterého se mění funkctionalita je považováno za antipattern - navrhuju bod odebrat

2024-01-28 12:13 UTC, holubond commented on 2_kvalita_kodu.md
> +    - Příklad: Máte třídu ReportGenerator s metodou generateReport. Chcete přidat nový typ reportu. Místo úpravy ReportGenerator, vytvoříte novou třídu FinancialReportGenerator, která rozšiřuje Repor
Doporučuju používat `inline blocky` pro kód, je to pak čitelnější. U metod nezapomeň na závorky.

Použití dědičnosti je zároveň celkem kontroverzní, často dělá kód hůře čitelný. Navrhuju přidat i příklad s použitím rozhraní.

Obecně pro tyto příklady prosím použij [collapsible](https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab), na pochopení se to hodí, ale při učení se to může zbytečně zabírat prostor na stránce.

2024-01-28 12:13 UTC, holubond commented on 2_kvalita_kodu.md
> +    - Příklad: Máte třídu Bird s metodou fly. Třída Duck je podtřídou Bird a může používat metodu fly. Ale když vytvoříte třídu Ostrich (pštros), který je také ptákem, nemůže používat metodu fly, pro
Použij inline blocky pro kód, u metod nezapomeň na závorky. Zároveň bych to uvedl jako *Příklad porušení LSP:*.

Použij prosím collapsible.

2024-01-28 12:13 UTC, holubond commented on 2_kvalita_kodu.md
> +    - Příklad: Místo jednoho velkého rozhraní Vehicle s metodami jako drive(), fly(), a sail(), ISP by doporučil rozdělit toto rozhraní na několik menších, jako LandVehicle, AirVehicle, a WaterVehicl
Použij blocky pro kód a collapsible.

2024-01-28 12:13 UTC, holubond commented on 2_kvalita_kodu.md
> +    - Například, pokud máte třídu Car závislou na konkrétní třídě GasEngine, změna na elektrický motor by vyžadovala změnu v třídě Car. Ale pokud Car závisí na abstraktním rozhraní Engine, lze snadno
Uveď to obdobně jako předchozí příklady, ať to máme jednotné, použij collapsible a blocky pro kód.

> závisí na ~~abstraktním~~ rozhraní

Rozhraní není abstraktní, to mohou být v OOP akorát třídy.

2024-01-28 12:13 UTC, holubond commented on 2_kvalita_kodu.md
> +- ideálně by měl testování provádět někdo jiný, než autor testovaného kódu - tohle je důležité hlavně při black box metodách, u unit testů je dost časté, že je píše sám vývojář
Toto bych to pro jistotu nezmiňoval před komisí, pokud pro to nemáš dobré argumenty... navrhuju jít bezpečnější variantou a nechat to v původním znění.

2024-01-28 12:13 UTC, holubond commented on 2_kvalita_kodu.md
> +- v Pythonu existuje knihovna hypothesis - ta dokáže generovat kombinaci různých zajímavých vstupů pro testy (větší než 0, blízko maximální hodnotě daného typu atd.) a kontrolovat nějaké predikáty, k
Navrhuju odebrat, je to příliš specifické pro jeden jazyk a jde to do detailů. S takovou bychom časem v dokumentu rozebírali veškeré možné technologie a blbě by se v tom hledaly důležité obecné věci.

2024-01-28 12:13 UTC, holubond commented on 2_kvalita_kodu.md
> +- je velmi časté vyvíjet další nezávislý systém/software na validaci/testování nějakého většího produktu - automatizovatelnost různých scénářů a i interní nástroj, který dokáže zajistit větší kvalitu
Nesouhlasím... proč vyvíjet další systém pro testování, když můžeš použít E2E testy skrz Playwright?

2024-01-28 12:13 UTC, holubond commented on 2_kvalita_kodu.md
> +- pokud jsou dev/test týmy odděleny, dost často probíhá psání těchto testů paralelně -> developeři tvoří danou feature a zároveň se na ni připravují i automatizované testy podle popsaného scénáře ->
Určitě ne, akceptační testy řešíš se zákazníkem. Často ani nemusí být automatizované...

2024-01-28 12:13 UTC, holubond commented on 2_kvalita_kodu.md
> +- u velkých produktů mohou existovat speciální týmy, které mají za úkol validaci kvality produktu. Ty nejen tvoří testy a scénáře, ale mohou vyvíjet i vnitřní infrastrukturu na automatizování celého
Jasně, ale už je to specifické pro velké produkty, tedy nepatří to jako odrážka pod to, z čeho se skládá proces řízení kvality ve vývoji SW systémů. Navrhuju pro jednoduchost textu odebrat.

2024-01-28 12:13 UTC, holubond commented on 2_kvalita_kodu.md
> +    - Level 5 Optimalizující - Organizace se neustále zlepšuje a optimalizuje své procesy na základě shromažďovaných měření a zjištění.
Nechme původní variantu, vím že jsem to tehdy psal podle přednášky a teď nemám úplně čas na to to dohledávat. Navíc některé věci vynecháváš (třeba míru odhadnutelnosti ceny produktu). Pokud to chceš přepsat, udělej separé feature branch.

2024-01-28 12:13 UTC, holubond commented on 2_kvalita_kodu.md
> +- fail-fast přístup - snažíme se detekovat problém ve vstupech, namísto abychom klidně akceptovali cokoliv a pak se divili při neočekávaném chování - příklad u typování JS/Pythonu -> mnoho chyb odhal
Fail-fast se řeší za běhu, příklad s typováním se k tomu nehodí.

2024-01-28 12:13 UTC, holubond commented on 4_projektove_rizeni.md
> +Schvalovací Procesy: Procesy, které řídí schválení a změny v projektu.
Toto ve zkratce už vysvětluju výše... pokud to chceš přece jen přidat, udělej to jako collapsible s názvem `Více o Project Charteru`, nebo tak něco.

2024-01-28 12:13 UTC, holubond commented on 4_projektove_rizeni.md
> +Zatímco Project Charter je výchozím bodem, který dává projektu zelenou a definuje jeho hlavní obrysy, PID je rozsáhlejší a podrobnější dokument, který slouží jako základ pro řízení a provedení projek
Toto víceméně říkám v prvním odstavci. Pokud chceš přece jen zdůraznit rozdíly, dej je na konec prvního odstavce, protože tady už řeším něco jiného.

2024-01-28 12:13 UTC, holubond commented on 4_projektove_rizeni.md
> +- **Feature groomingy** - krátké meetingy k jednotlivým featurám, kde jsou přítomni všichni důležití lidé a zhodnocují se rizika a implementace
Toto bylo v přednáškách? Zní to spíš jako specifikum vaší firmy, já se s tímto třeba setkávám poprvé...

2024-01-28 12:13 UTC, holubond commented on 4_projektove_rizeni.md
> +        - tvorba SLA - SLA je velmi často definované již v PID a zde se na něj jen přechází po dodání projektu
Ok, validní point. Přidáš zmínku o SLA do PID a upravíš to, aby tu byla jen zmínka o začátku platnosti SLA?

2024-01-28 12:13 UTC, holubond commented on img/p2p.png
Toto jde až příliš zbytečně do ne zcela podstatného detailu, zahlcuje to dokument.

2024-01-28 12:13 UTC, holubond commented on 6_pocitacove_site.md
> +![](img/p2p.png)
Myslím, že ten obrázek jde zbytečně do detailu a řeší jen ne příliš podstatnou hierarchii. Navrhuju odstranit.

2024-01-28 12:13 UTC, holubond commented on 6_pocitacove_site.md
> +Další důležitou vlastností P2P sítí je, jakým způsobem vnitřně dělí mezi sebou data. U nestrukturovaných sítí to není známo, pokud chceme nějaká data, tak se musíme zeptat celé sítě, jestli je někdo
Rozumím, to je určitě fajn zmínit. Co to trochu zestručnit, třeba takto:

### Distribuce dat v P2P sítích

**Nestrukturované sítě** - Je nutné se ptát, zda má někdo z peerů chtěná data (e.g. pomocí floodingu)

**Strukturované sítě**
...

2024-01-28 12:13 UTC, holubond commented on 6_pocitacove_site.md
> +- **Ploché** - Vvploché struktuře jsou všechny prvky nebo uzly považovány za rovnocenné, bez hierarchického uspořádání. Každý uzel má stejné schopnosti a odpovědnosti, a neexistují žádné centrální ne
Toto je popsáno v odrážce
> **Vrstvy** - peeři se organizují do vrstev...
 
Pro přehlednost navrhuju odebrat.

2024-01-28 12:13 UTC, holubond commented on 7_distribuovane_systemy.md
> +**Hexagonal/Microkernel/component-based** - základní aplikace poskytuje minimální funkcionalitu, zbytek se dodává skrz plug-in komponenty komunikující přes předdefinované api. Komponenty je možné pří
Oba rody - *kompoment* i *komponenta* jsou v pohodě - ponechme původní variantu

2024-01-28 12:13 UTC, holubond commented on 7_distribuovane_systemy.md
> +Hlavním rozdílem je, že centralizovaná architektura shromažďuje data a logiku na jednom místě, distribuovaná architektura rozptyluje logiku do více samostatných komponent (běžících třeba i na samosta
Oba rody - *kompoment* i *komponenta* jsou v pohodě - ponechme původní variantu

2024-01-28 12:13 UTC, holubond commented on 7_distribuovane_systemy.md
> +
To vše je víceméně řešeno v odstavci výše, nevidím důvod přidávat další text a dělat dokument méně přehledný.

2024-01-28 12:13 UTC, holubond commented on 7_distribuovane_systemy.md
> +Opakované Použití Služeb: Služby jsou navrženy tak, aby byly obecné a znovu použitelné pro různé účely, což snižuje redundantnost a usnadňuje údržbu.
Nemusí být vždy pravda a mnohdy to ani není kýžené - redundance je často v pohodě, protože díky ní snižuješ riziko, že při úpravě rozbiješ jiné systémy.

2024-01-28 12:13 UTC, holubond commented on 7_distribuovane_systemy.md
> +
Technologie jsou uvedené v průběhu dokumentu a tak nějak očekávám, že je studenti budou znát, nebo si je vyhledají. Schválně jsem se takto zjednodušeným popisům vyhýbal, protože se obávám, že pokud student technologii zmíní, bude komise chtít vědět detaily, pro které jsou tyto popisy stejně zbytečné. 

Navrhuju tuto sekci odebrat a případně dát ke zmínkám technologií odkazy na solidní rychlé vysvětlení, e.g. 100 seconds videa od Fireship.

2024-01-28 12:13 UTC, holubond commented on img/image.png
Toto nikde nepoužíváš, stejný obrázek je `img/cap.png`

2024-01-28 12:13 UTC, holubond commented on ops_1_bezpecna_infrastruktura.md
> +
Pod název napiš svoje autorství

*Vypracoval @simonf-dev*

2024-01-28 12:13 UTC, holubond commented on ops_2_cloud_computing.md
> +# Cloud computing
Pod název napiš svoje autorství

*Vypracoval @simonf-dev*

2024-01-28 12:13 UTC, holubond commented on ops_3_operacni_systemy.md
> +> Operační systém UNIX, fungování jádra, správa paměti a zařízení jádrem. Základní konfigurace, správa uživatelů, síťové služby. Principy vývoje a vývojové prostředí v UNIXu, práce s procesy, se soub
Přidej název, pod něj napiš svoje autorství

*Vypracoval @simonf-dev*

2024-01-28 12:13 UTC, holubond commented on ops_4_nosql_databaze.md
> +# NoSQL databáze
Pod název napiš svoje autorství

*Vypracoval @simonf-dev*

2024-01-28 12:13 UTC, holubond commented on ops_1_bezpecna_infrastruktura.md
> +### Aspekty ovlivňující bezpečnost systému na úrovni jeho infrastruktury
Zkus prosím dodržovat konvence v dokumentu - platí pro vše z části OPS. 

Například:
- části explicitně zmíněné v otázce (a sekce dodatečných poznámek) jsou uvedeny nadpisech druhé úrovně (`##`). Obecně jedeš s nadpisy celkem freestyle...
- text by měly být co nejvíc stručné, výstižné, straight to the point. Ukecanost nechme docům, toto by měl být materiál, nabitý obsahem - formátem jde spíš o dokumentaci, než o knihu. **Obecně známé věci nevysvětlujeme**, akorát to ubírá přehlednosti dokumentu. Pokud je koncept vysvětlen v jiné sekci, hodíme [odkaz]().
- klíčové je, aby se v dokumentu dalo dobře hledat a dobře se četl
- pokud rozebíráme body nějakého textu, použijeme odrážky, je tak jasné, že se daný blok vztahuje k předešlému textu. Musí být jasná hierarchie bloků textu, kromě odrážek je fajn si hrát i s odsazením.
- každá odrážka by měla být nezávislá na ostatních odrážkách stejné úrovně
  - v případě potřeby uděláme hierarchii odrážek
- je fajn se vyhýbat velkým jednolitým blokům textu, takové se špatně čtou a ještě hůř se v nich něco hledá. Důležité části můžeme třeba **zvýraznit**, zvlášť důležité části (třeba definice) dáme samostatně.
- dodržujeme [markdown best practices](https://www.markdownguide.org/basic-syntax/) - často ti chybí prázdné řádky mezi bloky textu či nadpisy, jindy jich tam máš moc
- **vyvarujeme se slangu** a anglikanismům, to komise nemá ráda

V následujících komentářích ti zkusím naznačit to s čím mám problém, obdobně je to v celém dokumentu - opravit to chce globálně.

2024-01-28 12:13 UTC, holubond commented on ops_1_bezpecna_infrastruktura.md
> +Ochrana hardwarových komponent, datových center a dalších fyzických prostředků před neoprávněným přístupem, poškozením nebo krádeží. Opatření pro vyšší bezpečnost mohou zahrnovat správné nastavení př
Podle konvencí v dokumentu navrhuju přepsat to na

```
## Aspekty ovlivňující bezpečnost systému na úrovni jeho infrastruktury

- **Fyzická bezpečnost** - ... (co nejstručnější text, nevysvětlujeme obecně známe koncepty. Pokud je koncept rozebrán jinde, hodíme odkaz na daný dokument, e.g. [Více v otázce ...](link))
- **Zabezpečení dat** - ...
...
```

2024-01-28 12:13 UTC, holubond commented on ops_1_bezpecna_infrastruktura.md
> +Opatření k ochraně dat uložených v systému. Zvyšování můžeme dělat například šifrováním, které ma za úkol znemožnit útočníkům získání hodnotných dat. Efektivní správa šifrovacích klíčů je zásadní pro
> například šifrováním, které ma za úkol znemožnit útočníkům získání hodnotných dat.

Vysvětluješ co je šifrování, to je obecně známé a rozebírá se v jiné otázce.

2024-01-28 12:13 UTC, holubond commented on ops_1_bezpecna_infrastruktura.md
> +Opatření k ochraně dat uložených v systému. Zvyšování můžeme dělat například šifrováním, které ma za úkol znemožnit útočníkům získání hodnotných dat. Efektivní správa šifrovacích klíčů je zásadní pro
> Dnes je to běžné v cloudech, kde na to existují speciální resources.

Typická otázka od komise: *Jaké speciální zdroje? A nepoužívejte slangová slova...*

Přidej příklad.

2024-01-28 12:13 UTC, holubond commented on ops_1_bezpecna_infrastruktura.md
> +Jako příklad je také solení hesel. V historii se mnohokrát stalo, že unikly databáze uživatelů a solení pomohlo před odhalením hesel uživatelů v raw formě.
> V historii se mnohokrát stalo, že unikly databáze uživatelů a solení pomohlo před odhalením hesel uživatelů v raw formě.

Nadbytečná informace

2024-01-28 12:13 UTC, holubond commented on ops_1_bezpecna_infrastruktura.md
> +VPN umožňuje bezpečné připojení k síti přes veřejný internet tím, že šifruje data, která jsou přenášena mezi uživatelem a síťovými zdroji. To je zvláště důležité pro vzdálené pracovníky, kteří potřeb
To samé přece dělá libovolné šifrované spojení, třeba HTTPS, ne? Hodilo by se víc rozebrat výhody VPN...

2024-01-28 12:13 UTC, holubond commented on ops_1_bezpecna_infrastruktura.md
> +Rozdělení sítě na menší části (segmenty) může pomoci omezit šíření škodlivého softwaru a zvýšit výkon tím, že se oddělí citlivé oblasti sítě od ostatních. Využití lze například najít při testování šk
Zvýšit výkon? To jako jak?

2024-01-28 12:13 UTC, holubond commented on ops_1_bezpecna_infrastruktura.md
> +- Phising - tyto útoky zahrnují posílání podvodných e-mailů, které se zdají pocházet z důvěryhodných zdrojů, s cílem získat citlivé informace, jako jsou přihlašovací údaje a čísla kreditních karet. S
*Phishing

2024-01-28 12:13 UTC, holubond commented on ops_1_bezpecna_infrastruktura.md
> +- DDOS - cílem těchto útoků je přetížit webové servery nebo sítě tak, aby se staly nedostupnými pro legitimní uživatele. Například v roce 2016 byl proveden masivní DDoS útok na službu Dyn, což vedlo
To by byl i DoS. U DDoSu je klíčová ta distribuovanost.

2024-01-28 12:13 UTC, holubond commented on ops_1_bezpecna_infrastruktura.md
> +- DDOS - cílem těchto útoků je přetížit webové servery nebo sítě tak, aby se staly nedostupnými pro legitimní uživatele. Například v roce 2016 byl proveden masivní DDoS útok na službu Dyn, což vedlo
*Netflixu

2024-01-28 12:13 UTC, holubond commented on ops_1_bezpecna_infrastruktura.md
> +##### Antivirusový systém
*Antivirový

2024-01-28 12:13 UTC, holubond commented on ops_1_bezpecna_infrastruktura.md
> +#### Slabiny a Zranitelnosti
Pod nadpisem 2. úrovně je nadpis 4. úrovně?

2024-01-28 12:13 UTC, holubond commented on ops_1_bezpecna_infrastruktura.md
> +**Shromažďování informací**: Získávání dat o útoku, jako jsou logy, sieťové pakety, systémové záznamy a incidentní zprávy, které poskytují kontext pro analýzu.
> sieťové pakety

to jsi odněkud kopíroval, že to je najednou slovensky? :D

2024-01-28 12:13 UTC, holubond commented on ops_2_cloud_computing.md
> +- **Funkce**: Alokuje virtuální stroje (VM) podle požadavků zákazníka, odstínění od manuálního nastavení sítě, firewallu a hardwaru. Samotný software jako instalace dockeru a nastavování prostředí pr
Ne nutně virtuální, mnohé platformy postytují i dedikované stroje

2024-01-28 12:13 UTC, holubond commented on ops_2_cloud_computing.md
> +- **Nevýhody**: Závislost na externím systému, potřeba vlastní konfigurace a znalost požadavků. Ve výsledku není extra moc automatizované, je to podobné jako kdybychom dostali od nějakého hostingu př
> Ve výsledku není extra moc automatizované, je to podobné jako kdybychom dostali od nějakého hostingu přístup k virtuálnímu stroji/mašině.

Nesouhlasím, když použiješ Terraform - určitě by si zasloužil zmínku.

2024-01-28 12:13 UTC, holubond commented on ops_2_cloud_computing.md
> +- **Příklady**: Azure Compute, HPC, GCP Compute Engine, Azure Storage managed disk, Google Persistent Disk.
Nejsou to už jednotlivé služby? Myslel jsem, že tady by měly být AWS, Azure, GCP, Linode, Hetzner...

2024-01-28 12:13 UTC, holubond commented on ops_2_cloud_computing.md
> +- **Definice**: Kompletní vývojářské prostředí v cloudu. Píšeme aplikaci dle nějakého protokolu (C#, Python aplikace) a cloud nasazení vyřeší již kompletně za nás. Je možné využívat a instalovat depe
> nějakého protokolu

protokolu?

2024-01-28 12:13 UTC, holubond commented on ops_2_cloud_computing.md
> +- **Definice**: Kompletní vývojářské prostředí v cloudu. Píšeme aplikaci dle nějakého protokolu (C#, Python aplikace) a cloud nasazení vyřeší již kompletně za nás. Je možné využívat a instalovat depe
> Je možné využívat a instalovat dependence pro projekt.

to přece můžeš všude...

2024-01-28 12:13 UTC, holubond commented on ops_2_cloud_computing.md
> +- **Funkce**: Odstínění od O/S,middleware úrovně (neřešíme záplaty systému, instalování potřebných dependencí). Cloud poskytuje celkové nastavení a deployment pro aplikaci, stačí jen nahrát kód do re
> neřešíme záplaty systému

systému ano, platformy ne

2024-01-28 12:13 UTC, holubond commented on ops_2_cloud_computing.md
> +- **Příklady**: Azure Web App, GCP Cloud Run, Azure Storage, Amazon S3, Google Cloud Storage.
Hodilo by se zmínit obecně známé Heroku, příladně Dokku

2024-01-28 12:13 UTC, holubond commented on ops_2_cloud_computing.md
> +nějak sem to opravil, lepší?
?

2024-01-28 12:13 UTC, holubond commented on ops_2_cloud_computing.md
> +#### Materializované zobrazení vs cache-aside
> Materializované zobrazení

máš na mysli pohled?

2024-01-28 12:13 UTC, holubond commented on ops_2_cloud_computing.md
> +**Cache-Aside** má podobné využití jako materalizované zobrazení, je zde však mnoho rozdílů. Cache-aside vzor nepředpočítává data a jen cachuje ty, které si uživatel vyžádal -> není potřeba dávat ste
zmínit redis, která se pro toto často používá?

2024-01-28 12:13 UTC, holubond commented on ops_2_cloud_computing.md
> +
Proč tolik volných řádků?

2024-01-28 12:13 UTC, holubond commented on ops_2_cloud_computing.md
> +klíče:
proč je to na novém řádku?

2024-01-28 12:13 UTC, holubond commented on ops_2_cloud_computing.md
> +nebo aplikační server poskytuje uživateli klíč, pomocí kterého může k souboru přistoupit. Tato komunikace už jde mimo aplikační server:
Proč to není v jednom odstavci?

2024-01-28 12:13 UTC, holubond commented on ops_2_cloud_computing.md
> +Ve světě cloudových aplikací je často výhodné využívat asynchronní zpracování zpráv, což umožňuje efektivnější a škálovatelnější architekturu. Asynchronní zpracování je zvláště užitečné pro dlouhotrv
Pro toto není nutné použít Paas, často se pro takové věci použije kubernetes. Hodily by se příklady...

2024-01-28 12:13 UTC, holubond commented on ops_2_cloud_computing.md
> +Ve světě cloudových aplikací je často výhodné využívat asynchronní zpracování zpráv, což umožňuje efektivnější a škálovatelnější architekturu. Asynchronní zpracování je zvláště užitečné pro dlouhotrv
Ne vždy jsou služby microservices... bacha na zavádějící pojmy.

2024-01-28 12:13 UTC, holubond commented on ops_2_cloud_computing.md
> +Využívá fronty, kde se ukládají zprávy a potom má subscribery, kteří zprávy zpracovávají a dělají požadované akce. U microservices dokážeme udělat logiku tak, že se microservices spouští jen podle to
Chybí příklady technologií

2024-01-28 12:13 UTC, holubond commented on ops_2_cloud_computing.md
> +Mikroslužby jsou architektonický styl vývoje softwaru, kde aplikace jsou rozděleny do malých, nezávislých služeb. Každá mikroslužba je zaměřena na jednu specifickou funkcionalitu a funguje autonomně.
Chybí klíčový bod - mikroslužba má vlastní databázi

2024-01-28 12:13 UTC, holubond commented on ops_2_cloud_computing.md
> +PaaS (Platform as a service) je kategorie cloudových služeb, která poskytuje platformu umožňující zákazníkům vývoj, spuštění a správu aplikací bez složitostí spojených s budováním a údržbou infrastru
> Pokud máme například nějakou Python aplikaci, tak dodržíme nějaké protokoly, kde máme sepsané dependence, jaký je entrypoint aplikace a více neřešíme.

? Protokoly?

2024-01-28 12:13 UTC, holubond commented on ops_2_cloud_computing.md
> +**Amazon Web Services (AWS)**: Služba od Amazonu, která automatizuje nasazení aplikací v cloudovém prostředí. Podporuje různé programovací jazyky a frameworky, jako jsou Java, .NET, PHP, Node.js, Pyt
AWS je PaaS? Docker je jazyk/framework?

2024-01-28 12:13 UTC, holubond commented on ops_2_cloud_computing.md
> +Ještě více rozbíjí aplikaci na aplikační úrovni. U PaaS většinou nasazujeme celou aplikaci, nebo její větší komponentu (celý backend, celý plugin pro aplikaci). U FaaS píšeme jen konkrétní funkci/end
FaaS je zkratka pro co? Taky se tomu říká serverless... hodily by se příklady technologií

2024-01-28 12:13 UTC, holubond commented on ops_2_cloud_computing.md
> +##### Výkonnost
Nadpisy 2. a 5. úrovně hned po sobě?

2024-01-28 12:13 UTC, holubond commented on ops_2_cloud_computing.md
> +**Testování zátěže**: V cloudu je nutné vědět, jakou předpokládanou zátěž bude aplikace obsluhovat. Následně je vhodné testovat jak se při této zátěži bude aplikace chovat a zda je schopná ustát větš
To ale platí i pro necloudová prostředí... chtělo by to rozebrat hlavně specifika pro cloud, obecně máme tyto věci probrané v jiné otázce.

2024-01-28 12:13 UTC, holubond commented on ops_2_cloud_computing.md
> +**Distribuovaná architektura**: Při návrhu aplikace, je vhodné rozdělit aplikaci tak, abychom mohli jednotlivé její komponenty škálovat nezávisle. Pokud správně aplikaci rozdělíme, tak můžeme flexibi
Jak konkrétně? Chtělo by to zmínit oddělení aplikační vrstvy od databáze, aplikaci lze pak díky bezstavovosti nasadit vícekrát...

2024-01-28 12:13 UTC, holubond commented on ops_2_cloud_computing.md
> +**Redundantní nasazení**: Cloud často nabízí v základu vysokou dostupnost, ale v některých krajních případech i toto může být nedostatečné. Pokud požadujeme velmi vysokou dostupnost aplikace tak je v
Dostupností se myslí i výpadek služby třeba z důvodu neošetřené výjimky...

2024-01-28 12:13 UTC, holubond commented on ops_4_nosql_databaze.md
> +- jiný přístup ukládání dat, který se liší od relačních DB
jak?

2024-01-28 12:13 UTC, holubond commented on ops_4_nosql_databaze.md
> +- hlavně pro big data
? myslíš, že je dobrý nápad dělat datové sklady v NoSQL databázích?

2024-01-28 12:13 UTC, holubond commented on ops_4_nosql_databaze.md
> +- nemají pevnou schému
*pevné schéma

2024-01-28 12:13 UTC, holubond commented on ops_4_nosql_databaze.md
> +- **Sharding** - data rozdělujeme podle nějakých pravidel, můžeme mít například primární klíč, podle kterého data rozdělujeme na uzly a rozkládáme zátěž
to už jsi vysvětloval jinde - rozhodni se kde to vysvětlíš, na druhé místo hoď odkaz

2024-01-28 12:13 UTC, holubond commented on ops_4_nosql_databaze.md
> +- u shardingu je klasické používat hash a např. kruh, kde každý uzel má na starost část kruhu
Přidej odsazení, když mluvíš o obsahu předchozí odrážky

2024-01-28 12:13 UTC, holubond commented on ops_4_nosql_databaze.md
> +- existují **vnodes**, které implementují to, že jsou dané segmenty ještě víc "rozsekány" a každý uzel má na starost více menších částí, rovnoměrněji dokáže distribuovat data mezi uzly a reagovat na
Co to je? Virtual nodes?

2024-01-28 12:13 UTC, holubond commented on ops_4_nosql_databaze.md
> +#### Master-slave replikace
`Master-slave replikace` je součástí `2PC`? Z textu to není zřejmé... Pokud ne, proč je to v hierarchii nadpisů pod sebou?

2024-01-28 12:13 UTC, holubond commented on ops_4_nosql_databaze.md
> +- jsou různé úrovně izolace:
Tyto úrovně jsou i v SQL světě, ne?

2024-01-28 12:13 UTC, holubond commented on ops_4_nosql_databaze.md
> +#### PC
Co znamená PC?

2024-01-28 12:13 UTC, holubond commented on ops_4_nosql_databaze.md
> +#### PA
Co znamená PA?

2024-01-28 12:13 UTC, holubond commented on ops_4_nosql_databaze.md
> +- Graph based - Umožňují reprezentaci a dotazování komplexních vztahů mezi daty. Neo4j a Amazon Neptune jsou příklady grafových databází. Dokážou dost dobře implementovat vztahy mezi entitami. Jan má
Toto všechno znovu vysvětluješ později, je to dokonce součástí otázky - navrhuju to tady smazat.

2024-01-28 12:13 UTC, holubond commented on ops_4_nosql_databaze.md
> +- Riak také nabízí text search
toto jsou 3 odrážky, které spolu souvisí... udělej hierarchii

2024-01-28 12:13 UTC, holubond commented on ops_4_nosql_databaze.md
> +- základní struktura údajů je dokument
> struktura údajů

struktura dat?

2024-01-28 12:13 UTC, holubond commented on ops_4_nosql_databaze.md
> +- jelikož podporuje vnořené dokumenty a dá se říct agregáty, tak je to **denormalizovaná schéma**
Denormalizovan**é** - je to to schéma

2024-01-28 12:13 UTC, holubond commented on ops_4_nosql_databaze.md
> +- db je naše databáze, inventory je potom něco jako tabulka -> sdružuje podobné dokumenty do jedné **kolekce**
Odrážky pod sebou by měly být izolované

2024-01-28 12:13 UTC, holubond commented on ops_4_nosql_databaze.md
> +- o dost víc odlišné než předchozí typy
Kdyby nebyly odlišné, tak to není samostatná kategorie, ne? :)

2024-01-28 12:56 UTC, simonf-dev commented on 2_kvalita_kodu.md
> +    - u UI systému například dodržování standardů používání id/class názvů atd.
automatizace  pomocí frameworků, protože ti změny nerozbíjí automatizované scénáře

2024-01-28 12:59 UTC, simonf-dev commented on 2_kvalita_kodu.md
> +        - důležitá je konzistence napříč codebase (ideálně stavěná na standardech daného jazyka) - například můžu definovat, že `check*()` metody vrací true/false a `verify*()` vyhazují vyjímky
Dopíšu, že se jedná o specifickou věc v Pythonu

2024-01-28 13:00 UTC, simonf-dev commented on 2_kvalita_kodu.md
> +    - např. v Pythonu (a jiných jazycích) se dost často vyplácí přidávat k existujícím funkcím optional variables -> funkce se pro existující volání chová stejně, ale se změnou nového atributu je mož
Proto je uveden Python jako příklad, smažu komentář ohledně jiných jazyků

2024-01-28 13:02 UTC, simonf-dev commented on 2_kvalita_kodu.md
> +- je velmi časté vyvíjet další nezávislý systém/software na validaci/testování nějakého většího produktu - automatizovatelnost různých scénářů a i interní nástroj, který dokáže zajistit větší kvalitu
Protože jsou frameworky dost často nedostačující a buduješ systém kolem nich. Navíc nejde jen o webové aplikace, testují se různě rozsáhlé a velké systémy.

2024-01-28 13:04 UTC, simonf-dev commented on 2_kvalita_kodu.md
> +- u velkých produktů mohou existovat speciální týmy, které mají za úkol validaci kvality produktu. Ty nejen tvoří testy a scénáře, ale mohou vyvíjet i vnitřní infrastrukturu na automatizování celého
Proto se tam uvádí, že je to specifické pro velké produkty. Je to segment kvality kódu.

2024-01-28 13:08 UTC, simonf-dev commented on 6_pocitacove_site.md
> +![](img/p2p.png)
Jakou přesně nepodstatnou hierarchii? Právě jsou tam ukázané různé typy dělení P2P

2024-01-28 13:38 UTC, simonf-dev commented on ops_1_bezpecna_infrastruktura.md
> +Jako příklad je také solení hesel. V historii se mnohokrát stalo, že unikly databáze uživatelů a solení pomohlo před odhalením hesel uživatelů v raw formě.
Je to příklad

2024-01-28 13:43 UTC, simonf-dev commented on ops_1_bezpecna_infrastruktura.md
> +VPN umožňuje bezpečné připojení k síti přes veřejný internet tím, že šifruje data, která jsou přenášena mezi uživatelem a síťovými zdroji. To je zvláště důležité pro vzdálené pracovníky, kteří potřeb
HTTPS je specifické pro weby a je to aplikační/transportní vrstva, VPN je síťová/transportní. Jde o jinou věc a moc nevidím důvod tu zmiňovat HTTPS,

2024-01-28 13:52 UTC, simonf-dev commented on ops_1_bezpecna_infrastruktura.md
> +**Shromažďování informací**: Získávání dat o útoku, jako jsou logy, sieťové pakety, systémové záznamy a incidentní zprávy, které poskytují kontext pro analýzu.
Jojo, občas sem zkopíroval text a potom zkracoval+upravoval, tak se to tam dostalo :D

2024-01-28 13:55 UTC, simonf-dev commented
Jelikož je připomínek dost, tak budu postupně odpovídat a upravovat věci, jak se je budu učit. Tudíž mi to asi zabere trošku víc času a budu to projíždět postupně. Dá mi to k těm věcem i lepší kontext rovnou.

2024-01-28 15:56 UTC, holubond commented
> Jelikož je připomínek dost, tak budu postupně odpovídat a upravovat věci, jak se je budu učit. Tudíž mi to asi zabere trošku víc času a budu to projíždět postupně. Dá mi to k těm věcem i lepší kontext rovnou. Lidi se zatím můžou OPS učit z PR a případně budu i rád, když některý věci opraví/upraví podle svýho. Nějak nelpím na přesný formě.

Ok, zažádej si o review až to bude ready.

2024-01-29 08:02 UTC, thes01 commented on ops_1_bezpecna_infrastruktura.md
> +### Aspekty ovlivňující bezpečnost systému na úrovni jeho infrastruktury
co takhle tyto rady hodit do contribution guide?

2024-09-05 03:57 UTC, closed without merging